-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.MAIN
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA MAIN;


-- ------------------------------------------------------------
-- DROP CONSTRAINTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" DROP PRIMARY KEY;

-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."OBSOLETE_PROMOTIONS";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."DEPRECATED_RATE_CARD";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."LEGACY_CUSTOMER_DATA";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."OLD_REPORTING_SUMMARY";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_SALES_FACT (
	SALE_ID NUMBER(18,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SALE_DATE DATE NOT NULL,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	PRODUCT_ID NUMBER(10,0) NOT NULL,
	CATEGORY_ID NUMBER(10,0),
	REGION VARCHAR(50),
	COUNTRY_CODE VARCHAR(3),
	QUANTITY NUMBER(10,0) NOT NULL DEFAULT 1,
	UNIT_PRICE NUMBER(18,4) NOT NULL,
	DISCOUNT_PCT NUMBER(6,4) DEFAULT 0,
	GROSS_AMOUNT NUMBER(18,2) NOT NULL,
	DISCOUNT_AMOUNT NUMBER(18,2) DEFAULT 0,
	NET_AMOUNT NUMBER(18,2) NOT NULL,
	TAX_AMOUNT NUMBER(18,2) DEFAULT 0,
	CURRENCY_CODE VARCHAR(3) DEFAULT 'USD',
	PAYMENT_METHOD_ID NUMBER(10,0),
	CHANNEL VARCHAR(50),
	IS_RETURNED BOOLEAN DEFAULT FALSE,
	RETURN_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint PK_NEW_SALES_FACT primary key (SALE_ID)
);

CREATE OR REPLACE TABLE NEW_APP_CONFIG (
	CONFIG_KEY VARCHAR(200) NOT NULL,
	CONFIG_VALUE VARCHAR(4000),
	VALUE_TYPE VARCHAR(20) DEFAULT 'STRING',
	ENVIRONMENT VARCHAR(20) NOT NULL DEFAULT 'ALL',
	DESCRIPTION VARCHAR(1000),
	IS_ENCRYPTED BOOLEAN DEFAULT FALSE,
	VALID_FROM DATE DEFAULT CURRENT_DATE(),
	VALID_TO DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_BY VARCHAR(100),
	check (VALUE_TYPE IN ('STRING','NUMBER','BOOLEAN','JSON','DATE')),
	check (ENVIRONMENT IN ('ALL','DEV','UAT','PROD')),
	constraint PK_NEW_APP_CONFIG primary key (CONFIG_KEY, ENVIRONMENT)
);

CREATE OR REPLACE TABLE NEW_AUDIT_LOG (
	LOG_ID NUMBER(18,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EVENT_TIME TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TABLE_NAME VARCHAR(200) NOT NULL,
	OPERATION VARCHAR(10) NOT NULL,
	RECORD_ID VARCHAR(100),
	OLD_VALUES VARIANT,
	NEW_VALUES VARIANT,
	CHANGED_BY VARCHAR(100),
	SESSION_ID VARCHAR(100),
	QUERY_ID VARCHAR(100),
	check (OPERATION IN ('INSERT','UPDATE','DELETE','TRUNCATE')),
	constraint PK_NEW_AUDIT_LOG primary key (LOG_ID)
);

CREATE OR REPLACE TABLE NEW_PAYMENT_METHOD (
	PAYMENT_METHOD_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	METHOD_NAME VARCHAR(100) NOT NULL,
	METHOD_CODE VARCHAR(20) NOT NULL,
	PROVIDER VARCHAR(100),
	IS_DIGITAL BOOLEAN DEFAULT FALSE,
	PROCESSING_FEE_PCT NUMBER(6,4) DEFAULT 0,
	CURRENCY_CODE VARCHAR(3),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint UQ_PAYMENT_METHOD_CODE unique (METHOD_CODE),
	constraint PK_NEW_PAYMENT_METHOD primary key (PAYMENT_METHOD_ID),
	constraint FK_PAYMENT_CURRENCY foreign key (CURRENCY_CODE) references UZAIR_PROD.MAIN.REF_CURRENCY(CURRENCY_CODE)
);

CREATE OR REPLACE TABLE NEW_CUSTOMER_SEGMENT (
	SEGMENT_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SEGMENT_NAME VARCHAR(200) NOT NULL,
	SEGMENT_CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(1000),
	MIN_REVENUE NUMBER(18,2) DEFAULT 0,
	MAX_REVENUE NUMBER(18,2),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(100),
	unique (SEGMENT_CODE),
	constraint PK_NEW_CUSTOMER_SEGMENT primary key (SEGMENT_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "CREATED_AT" COMMENT 'Record creation timestamp (UTC)';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICE_TYPE" COMMENT 'Type: LIST, WHOLESALE, PROMO, CONTRACT';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "IS_ACTIVE" COMMENT 'Soft delete flag';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "VALID_TO" COMMENT 'Inclusive end date; NULL means open-ended';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "VALID_FROM" COMMENT 'Inclusive start date of this price';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "MIN_QUANTITY" COMMENT 'Minimum order quantity for this price to apply';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "CURRENCY_CODE" COMMENT 'ISO 4217 currency code';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICING_ID" COMMENT 'Surrogate key — auto generated';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICE_AMOUNT" COMMENT 'Price in specified currency';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRODUCT_ID" COMMENT 'FK to PRODUCTS table';
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "MIDDLE_NAME" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "LOYALTY_TIER" VARCHAR(20) DEFAULT 'BRONZE';
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "NATIONALITY" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "LOYALTY_POINTS" NUMBER(10) DEFAULT 0;
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "PREFERRED_NAME" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "REFERRAL_CODE" VARCHAR(20);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "ADDR_LINE1" TO "ADDRESS_LINE_1";
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "ADDR_LINE2" TO "ADDRESS_LINE_2";
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "CUST_PHONE" TO "PHONE_NUMBER";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "QUANTITY_RESERVED" TO "QUANTITY_ON_HAND";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "QUANTITY_AVAILABLE" TO "QUANTITY_RESERVED";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "LAST_RECEIVED_AT" TO "LAST_COUNTED_AT";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "LAST_RECEIVED_AT" TIMESTAMP_NTZ;
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "AISLE" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "BIN" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "QUANTITY_AVAILABLE" NUMBER(12) NOT NULL DEFAULT 0;
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "SHELF" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "LEGACY_REF";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "QUANTITY_ON_HAND";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "LAST_COUNTED_AT";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "INTERNAL_CODE";
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "WEIGHT_KG" SET DATA TYPE NUMBER(10,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "UNIT_PRICE" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "DESCRIPTION" SET DATA TYPE VARCHAR(4000);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "PRODUCT_NAME" SET DATA TYPE VARCHAR(500);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "COST_PRICE" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "PRODUCT_CODE" SET DATA TYPE VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "SKU" SET DATA TYPE VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."FINANCIAL_TRANSACTIONS" ALTER COLUMN "TRANSACTION_DATE" SET DATA TYPE DATE;
ALTER TABLE "UZAIR_PROD"."MAIN"."FINANCIAL_TRANSACTIONS" ALTER COLUMN "AMOUNT" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD CONSTRAINT "UQ_INVENTORY_LOC" UNIQUE ("LOCATION_CODE");
ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" ADD CONSTRAINT "UQ_EMPLOYEE_PRIMARY_ROLE" UNIQUE ("EFFECTIVE_FROM");
ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" ADD PRIMARY KEY ("EFFECTIVE_FROM", "EMPLOYEE_ID", "ROLE_CODE");
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" SET COMMENT = 'Stores time-bounded pricing tiers for products across price types and currencies';
-- NOTE: Column default change on ORDERS (STATUS, PRIORITY) requires CREATE OR REPLACE
-- Snowflake does not support ALTER COLUMN SET DEFAULT for literal values on any table type.
CREATE OR REPLACE TABLE ORDERS (
	ORDER_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	ORDER_NUMBER VARCHAR(50) NOT NULL,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	ORDER_DATE TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
	PRIORITY VARCHAR(20) DEFAULT 'NORMAL',
	SHIPPING_ADDRESS VARCHAR(1000) NOT NULL,
	BILLING_ADDRESS VARCHAR(1000),
	CURRENCY_CODE VARCHAR(3) NOT NULL DEFAULT 'USD',
	SUBTOTAL NUMBER(18,2) NOT NULL DEFAULT 0,
	TAX_AMOUNT NUMBER(18,2) DEFAULT 0,
	SHIPPING_AMOUNT NUMBER(18,2) DEFAULT 0,
	TOTAL_AMOUNT NUMBER(18,2) NOT NULL DEFAULT 0,
	NOTES VARCHAR(2000),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint UQ_ORDERS_NUMBER unique (ORDER_NUMBER),
	constraint PK_ORDERS primary key (ORDER_ID),
	constraint FK_ORDERS_CURRENCY foreign key (CURRENCY_CODE) references UZAIR_PROD.MAIN.REF_CURRENCY(CURRENCY_CODE)
);

-- NOTE: Column default change on SUPPORT_TICKETS (STATUS) requires CREATE OR REPLACE
-- Snowflake does not support ALTER COLUMN SET DEFAULT for literal values on any table type.
CREATE OR REPLACE TABLE SUPPORT_TICKETS (
	TICKET_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TICKET_NUMBER VARCHAR(30) NOT NULL,
	CUSTOMER_ID NUMBER(10,0),
	SUBJECT VARCHAR(500) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	STATUS VARCHAR(30) DEFAULT 'NEW',
	PRIORITY VARCHAR(20) DEFAULT 'MEDIUM',
	CHANNEL VARCHAR(30),
	ASSIGNED_TO VARCHAR(100),
	RESOLVED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	check (STATUS IN ('NEW','OPEN','IN_PROGRESS','PENDING_CUSTOMER',
                                          'ESCALATED','RESOLVED','CLOSED','CANCELLED')),
	check (PRIORITY IN ('LOW','MEDIUM','HIGH','URGENT','CRITICAL')),
	check (CHANNEL IN ('EMAIL','PHONE','CHAT','PORTAL','SOCIAL','IN_PERSON')),
	constraint UQ_TICKET_NUMBER unique (TICKET_NUMBER),
	constraint PK_SUPPORT_TICKETS primary key (TICKET_ID)
);


-- ============================================================
-- END - 56 statement(s)
-- ============================================================